version: "v1.0"
name: v2 failing pipeline
semaphore_image: "docker"
switch:
  - name: stg
    pipeline_path: "./.stg.yml"
    auto: true
  - name: prod
    pipeline_path: "./.prod.yml"
blocks:
  - name: block1
    task:
      jobs:
        - name: job1
          commands:
            - echo foo
            - echo bar
        - name: job2
          commands:
            - echo baz
  - name: block2
    task:
      jobs:
        - name: failing job
          commands:
            - exit 127
        - name: job2
          commands:
            - echo baz
